version: '3'
services:
  backend:
    build: ./
    image: backend2
    container_name: itihad-back:1.0
    ports:
      - "1337:1337"

  frontend:
    build: ./frontend
    image: frontend2
    container_name: itihad-front:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend